name: 云端编译 llama.cpp CUDA 版

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装 CUDA 编译环境
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda_12.2.0_535.54.03_linux.run
          sudo sh cuda_12.2.0_535.54.03_linux.run --toolkit --silent
          echo "/usr/local/cuda-12.2/bin" >> $GITHUB_PATH
          
      - name: 编译 CUDA 版
        run: |
          cmake -B build -DGGML_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=50
          make -C build -j4
          
      - name: 打包成品
        run: |
          cd build/bin
          tar -zcvf llama-cuda.tar.gz ./*
          
      - uses: actions/upload-artifact@v4
        with:
          name: llama-cuda-bin
          path: build/bin/llama-cuda.tar.gz